
---

## ⚙️ PostgreSQL Setup

- Use `pgAdmin` to monitor DB inserts.
- Add DB credentials in `.env` file:

DATABASE_URL=postgresql://your_user:your_pass@localhost:5432/your_db


---

## ▶️ Running the App

```bash
python -m venv venv
source venv/bin/activate    # or venv\Scripts\activate
pip install -r requirements.txt

python run.py

Visit: http://127.0.0.1:5000

app:
  name: InsightPilot
  environment: development
  log_level: DEBUG

paths:
  upload_log_dir: uploads/logs
  upload_image_dir: uploads/images
  upload_video_dir: uploads/videos
  analysis_report_dir: analysis_reports
  task_log_csv: logs/task_log.csv
